//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int Id_Banned_Account { get; set; }
        public Nullable<System.DateTime> BannedDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
