//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlockusEntities : DbContext
    {
        public BlockusEntities()
            : base("name=BlockusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<ProfileConfiguration> ProfileConfiguration { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Results> Results { get; set; }
    }
}
