//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id_Report { get; set; }
        public string ReportDescription { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> Id_Complainant { get; set; }
        public Nullable<int> Id_Reported { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
